services:

  db:
    image: postgres:latest
    container_name: pgsql
    restart: always
    environment:
      POSTGRES_USER: mcadmin
      POSTGRES_PASSWORD: 5394
      POSTGRES_DB: mcdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: infra.labs@outlook.com
    ports:
      - "8080:8080"

volumes:
  pgdata:

  