services:
    semaphoreui:
        ports:
            - 3000:3000
        image: semaphoreui/semaphore:v2.17.26
        environment:
            SEMAPHORE_DB_DIALECT: mysql
            SEMAPHORE_DB_HOST: 192.168.8.153:3306
            SEMAPHORE_DB_NAME: minicloud_db
            SEMAPHORE_DB_USER: mcadmin
            SEMAPHORE_DB_PASS: 5394
            SEMAPHORE_ADMIN: mcadmin
            SEMAPHORE_ADMIN_PASSWORD: 5394
            SEMAPHORE_ADMIN_NAME: mcadmin
            SEMAPHORE_ADMIN_EMAIL: achintha.jayalal@outlook.com
            SEMAPHORE_PORT: "3000"
        volumes:
            - semaphore_data:/var/lib/semaphore
            - semaphore_config:/etc/semaphore
volumes:
    semaphore_data:
    semaphore_config: