[c_host]

192.168.8.150 ansible_user=mcadmin

[db]

192.168.8.151 ansible_user=mcadmin

[monitoring]

192.168.8.152 ansible_user=mcadmin

[control]

192.168.8.153 ansible_user=mcadmin

[backup]

192.168.8.154 ansible_user=mcadmin
