- name: install htop monitoring
  hosts: c_host, DB, monitoing, control
  become: yes
  tasks:
  - name: update cache
    apt:
      update_cache: yes
  
  - name: install htop
    apt:
      name: htop
      state: present


  - name: install tree
    apt:
      name: tree
      state: present
